### PR TITLE
Added link to an initial data catalog for explore + download

### PR DESCRIPTION
**Pull request by ajturner**
To assist in the registration and discovery of data, we configured a [Prep Open Data Site](http://prepdata.sdgs.opendata.arcgis.com/). This PR adds a simple link from the prototype to explore this catalog.

prepprototype

home___preparedness_for_resilience__climate_data

search_for_____preparedness_for_resilience__climate_data

### CODE REVIEW

**Comment by fgassert** [comment]
Hey @ajturner,
Awesome thanks for doing this work, we should definitely build this in. 
We may need to do some additional work down the road in terms of service integration and maintaining a consistent user experience. We can discuss next week.
Best,
F

**Comment by ajturner** [comment]
@fgassert the PR adds this capability. Do you want to merge it and we can update the UX in subsequent PR?

**Comment by fgassert** [comment]
Merge away

**Comment by eightysteele** [comment]
LGTM

**Pull request merged**
